# ACTION METADATA
# https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions

---
name: repostructure-action
author: '@flex-development'
description: Repository infrastructure as code
inputs:
  api:
    default: ${{ github.api_url }}
    description: Base URL of GitHub API
    required: false
  config:
    default: .github/infrastructure.yml
    description: Location of infrastructure configuration file relative to github.workspace
    required: false
  token:
    default: ${{ github.token }}
    description: Personal access token (PAT) used to authenticate GitHub API requests
    required: false
  workspace:
    default: ${{ github.workspace }}
    description: Path to current working directory
    required: false
runs:
  main: dist/main.mjs
  using: node20
branding:
  color: blue
  icon: settings
